apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8003   # acceso externo en localhost:8003
  selector:
    app: backend