apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8083   # acceso externo en localhost:8083
  selector:
    app: frontend
