apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ${env}
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: ${backend_nodeport}
  selector:
    app: backend
