apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ${env}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: ${frontend_nodeport}
  selector:
    app: frontend
