apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ${env}
spec:
  replicas: ${frontend_replicas}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ${frontend_image}
          ports:
            - containerPort: 8080
              hostPort: ${frontend_nodeport}
          env:
            - name: BACKEND_URL
              value: "http://backend.${env}.svc.cluster.local:8000"
