apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stg
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8002   # acceso externo en localhost:8002
  selector:
    app: backend