apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tuimagen/frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: BACKEND_URL
              value: "http://backend.stg.svc.cluster.local:8000"
