global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'dev-node'
    static_configs:
      - targets: ['192.168.49.2:8091']

  - job_name: 'dev-backend'
    static_configs:
      - targets: ['192.168.49.2:8001']

  - job_name: 'dev-frontend'
    static_configs:
      - targets: ['192.168.49.2:8081']
      
  - job_name: 'stg-node'
    static_configs:
      - targets: ['192.168.49.2:8191']

  - job_name: 'stg-backend'
    static_configs:
      - targets: ['192.168.49.2:8101']

  - job_name: 'stg-frontend'
    static_configs:
      - targets: ['192.168.49.2:8181']

  - job_name: 'prod-node'
    static_configs:
      - targets: ['192.168.49.2:8291']
  - job_name: 'prod-backend'
    static_configs:
      - targets: ['192.168.49.2:8201']
  
  - job_name: 'prod-frontend'
    static_configs:
      - targets: ['192.168.49.2:8281']
